### ISSUE TITLE
Questions ( and suggestion ): 

### ISSUE THREAD

**Issue by sebheitzmann** [prestigejo/lego-bundle#2]
/**
 * order components
 *
 * @Route("/oc/{suffix_route}")
 * @Method({"GET", "POST"})
 * @return array
 */

I think that you mean Sort Component ? 

The trait should be named ControllerTrait ?

Is the layout included in the bundle ? Which js / css composant is needed ? AdminLTE ?
 
Is the security component needed ? If i want another one ? Is the basic symfony user suffisant ? Why is this part in this bundle ?

**Comment by jorissae** [comment]
Yes but I think to change the name "component" to "brick" because the Lego component should not be confused with the Symfony component. Lego components are autonomous parts of a page.

- Sort is better than the order you are right. (I fix it)
- The name controllerTrait is better too. (I fix it)

The adminLTE layout is included.
I planned to minify in the same way as easyadmin (with compile_assets.sh).

You can use Fosuser. The bundle needs only the login of the route and the class of users.
The bundle includes
- login route + model
- logout route
- A command to create a basic user
- A template to create a basic user entity


The bundle includes this feature to help set up

Of course, you can disable it simply by deleting the lego_security routes
https://github.com/prestigejo/flex/blob/master/prestigejo/legobundle/0.2/config/routes/lego.yaml
